package org.usfirst.frc.team3950.robot.config;

public class DrivetrainConfig {
	public PIDF pidf;
	public int DT_NAVX_ERROR_THRESHOLD;
	public int DT_DRIVE_STRAIGHT_LOWER_POWER_LEFT;
	public int DT_DRIVE_STRAIGHT_HIGHER_POWER_RIGHT;
	public int DT_DRIVE_STRAIGHT_HIGHER_POWER_LEFT;
	public int DT_DRIVE_STRAIGHT_LOWER_POWER_RIGHT;
	public int DRIVE_DISTANCE_LOW_POWER;
	
	public void setPidf(PIDF pidf) {
		this.pidf = pidf;
	}
	public PIDF getPidf() {
		return this.pidf;
	}
	
/*	public void setDT_NAVX_ERROR_THRESHOLD(int DT_NAVX_ERROR_THRESHOLD) {
		this.DT_NAVX_ERROR_THRESHOLD = DT_NAVX_ERROR_THRESHOLD;
	}
	public int getDT_NAVX_ERROR_THRESHOLD() {
		return this.DT_NAVX_ERROR_THRESHOLD;
	}
	
	public void setDT_DRIVE_STRAIGHT_LOWER_POWER_LEFT(int DT_DRIVE_STRAIGHT_LOWER_POWER_LEFT) {
		this.DT_DRIVE_STRAIGHT_LOWER_POWER_LEFT = DT_DRIVE_STRAIGHT_LOWER_POWER_LEFT;
	}
	public int getDT_DRIVE_STRAIGHT_LOWER_POWER_LEFT() {
		return this.DT_DRIVE_STRAIGHT_LOWER_POWER_LEFT;
	}
	
	public void setDT_DRIVE_STRAIGHT_HIGHER_POWER_RIGHT(int DT_DRIVE_STRAIGHT_HIGHER_POWER_RIGHT) {
		this.DT_DRIVE_STRAIGHT_HIGHER_POWER_RIGHT = DT_DRIVE_STRAIGHT_HIGHER_POWER_RIGHT;
	}
	public int getDT_DRIVE_STRAIGHT_HIGHER_POWER_RIGHT() {
		return this.DT_DRIVE_STRAIGHT_HIGHER_POWER_RIGHT;
	}
	
	public void setDT_DRIVE_STRAIGHT_HIGHER_POWER_LEFT(int DT_DRIVE_STRAIGHT_HIGHER_POWER_LEFT) {
		this.DT_DRIVE_STRAIGHT_HIGHER_POWER_LEFT = DT_DRIVE_STRAIGHT_HIGHER_POWER_LEFT;
	}
	public int getDT_DRIVE_STRAIGHT_HIGHER_POWER_LEFT() {
		return this.DT_DRIVE_STRAIGHT_HIGHER_POWER_LEFT;
	}
	
	public void setDT_DRIVE_STRAIGHT_LOWER_POWER_RIGHT(int DT_DRIVE_STRAIGHT_LOWER_POWER_RIGHT) {
		this.DT_DRIVE_STRAIGHT_LOWER_POWER_RIGHT = DT_DRIVE_STRAIGHT_LOWER_POWER_RIGHT;
	}
	public int getDT_DRIVE_STRAIGHT_LOWER_POWER_RIGHT() {
		return this.DT_DRIVE_STRAIGHT_LOWER_POWER_RIGHT;
	}
	
	public void setDRIVE_DISTANCE_LOW_POWER(int DRIVE_DISTANCE_LOW_POWER) {
		this.DRIVE_DISTANCE_LOW_POWER = DRIVE_DISTANCE_LOW_POWER;
	}
	public int getDRIVE_DISTANCE_LOW_POWER() {
		return this.DRIVE_DISTANCE_LOW_POWER;
	}
	*/
}
